### ISSUE TITLE
[Errata]: link to example code has no example code

### ISSUE THREAD

**Issue by CheshireCat44** [raspberrypipress/gsw-micropython-on-raspberry-pi-pico-2e#1]
### Contact Details

riddings44@yahoo.co.uk

### What format of the book has this error? You may select more than one option.

Print

### Page Number or Section

Page v: (Welcome)

### Detailed description

"You can find this book's example code... at 
rptl.io/pico-resources-2e"

But they aren't there!

**Comment by CheshireCat44** [comment]
Thanks for fixing this. Typing in code takes me back to Easter 1980 when my very early BBC 'B' arrived and the main source of code was the "yellow pages" of the magazines 8-}
Philip 

Yahoo Mail: Search, organise, conquer 
 
  On Thu, 11 Jul 2024 at 15:23, Brian ***@***.***> wrote:   


Very sorry about that, @CheshireCat44. It's fixed now! You can find all the examples in the eg/ subdirectory.

**Comment by bjepson** [comment]
You're welcome! Those were the good old days. I have fond memories of ZX81 and Atari 400 type-in programs!
