### ISSUE TITLE
[Errata]: Misleading STR function 

### ISSUE THREAD

**Issue by Hubgit243** [raspberrypipress/gsw-micropython-on-raspberry-pi-pico-2e#10]
### Contact Details (optional, will be publicly viewable)

barbabrian@yahoo.co.uk

### What format of the book has this error? You may select more than one option.

Print

### Page Number or Section

125

### Detailed description

Not an error as such, but a confusing omission. There is a programme to turn the Pico into a self-contained thermometer by adding an LCD display. Below this, it says”we use the str function which converts the number to a string of characters”. But the programme does not have “str” in any line, just “f”, which is misleading.

**Comment by bjepson** [comment]
Thanks for reporting this. I'm closing this as a duplicate of #8.
